project:
  type: book

book:
  title: "The R Workshop Book"
  author: "[Rebecca L. Barter](https://www.rebeccabarter.com)"
  date: "12/27/2024"
  google-analytics:
    tracking-id: "G-QXD5CL0YRD"
  repo-url: https://github.com/rlbarter/r-workshop-book
  issue-url: https://github.com/rlbarter/r-workshop-book
  license: "[CC BY-NC-ND](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
  navbar: 
    title: "The R Workshop Book"
    left:
      - text: "Rebecca L. Barter"
        href: https://www.rebeccabarter.com
    tools:
      - icon: github
        menu:
          - text: Report Typo/Issue
            url:  https://github.com/rlbarter/r-workshop-book
  chapters:
    - index.qmd
    - part: "Getting Started"
      chapters:
        - 00_rstudio_quarto.qmd
    - part: "R Fundamentals"
      chapters:
        - 01_r_fundamentals.qmd
        - 02_types.qmd
        - 03_vectors.qmd
        - 04_data_frames.qmd
    - part: "The Tidyverse"
      chapters:
        - 05_dplyr.qmd
        - 06_ggplot2.qmd


format:
  html:
    theme: yeti
  pdf:
    documentclass: scrreprt



