# Preface {.unnumbered}

Welcome to *The R Workshop* Book by [Rebecca L Barter](www.rebeccabarter.com). 

This book was designed as a companion to two R workshops that I originally developed and taught at the University of Utah: "Introduction to R for Data Analysis", which I teach over 2 days, and "Advanced R for Data Analysis", which is just a 1 day workshop. So far, this book only contains the content for the first workshop, but keep an eye on this space as I'll be progressively releasing the advanced R workshop chapters.

This book, like the original workshops on which it is based, is designed to get you up and running using R for the analysis of tabular data (i.e., data that comes in a table) using the tidyverse, focusing on data manipulation and data visualization. Rather than teaching you everything there is to know about R, this book just teaches what you need to actually start doing data analysis within the modern "tidyverse" ecosystem.

My approach is a somewhat less fancy approach to teaching R than many of the existing modern R books out there, such as [R for Data Science](https://r4ds.hadley.nz/), which starts working with data and creating visualizations up front. These are great books, but I personally prefer to teach beginners in a more linear fashion, which takes a more step-by-step approach, starting with understanding how the programming language works and building up to fancy things like actually working with data. If you're looking to be inspired, *R for Data Science* is probably a better book for you. But if you're looking for a resource to give you the building blocks for learning R, starting with the absolute basics, then you're in the right place.

The R programming language is constantly evolving, and my goal is to keep this book up-to-date as new developments emerge.


## Teaching from this book

You are absolutely welcome to teach from this book however you like, but I do request that you provide appropriate attribution.



## Learn from me!

Feel free to reach out if you're interested in hiring me to teach custom versions of these workshops.




## Inspiration attribution


The original inspiration for the first parts of this book came from Software Carpentry, which is where I first encountered the gapminder dataset that is used throughout (however, the materials you will find in this book bear little-to-no resemblance to any of the R Software Carpentry workshops.)


## Errors, typos, and contributions

If you notice any errors or typos, feel free to let me know by filing an issue on the book's [GitHub repository](https://github.com/rlbarter/r-workshop-book).

## Get in touch

Feel free to email me at rlbarter at gmail dot com if you'd like to get in touch.